[openai]
api_key = "sk-your-api-key"

[prompts]
# Optional developer message injected before the user request.
developer_prompt = "You are the Intelligent Search Assistant."
# Optional defaults for the main textarea.
# default_user_prompt_id = "prompt_app_default_id"
# default_user_prompt_version = "1"

[prompts.prompt_app]
# Prompt asset used for the primary application routes.
id = "prompt_app_id"
version = "1"
variable_names = ["user_input"]
# Cache key reused for both routes (the app will append the route identifier).
cache_key = "isa-app"

[prompts.prompt_classifier]
# Prompt asset used by the background classifier.
id = "prompt_classifier_id"
version = "1"
variable_names = ["user_input"]
model = "gpt-4.1-mini"
cache_key = "isa-classifier"
