[openai]
api_key = "sk-your-api-key"

[prompts.prompt_app]
# Prompt asset used for the primary application routes.
id = "prompt_app_id"
variable_names = ["user_input"]
# Cache key reused for both routes (the app will append the route identifier).
cache_key = "isa-app"

[prompts.prompt_creative]
# Prompt asset used for the creative agent routes.
id = "prompt_creative_id"
variable_names = ["user_input"]
# Cache key reused for creative responses.
cache_key = "isa-creative"

[prompts.prompt_classifier]
# Prompt asset used by the background classifier.
id = "prompt_classifier_id"
variable_names = ["user_input"]
cache_key = "isa-classifier"
